import { getCurrentUser } from "@/services/user";
import { Metadata } from "next";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser = await getCurrentUser()
  if (currentUser?.role === "USER" || !currentUser) return notFound()

  return (
    <main>
      {children}
    </main>
  )
}
